// <auto-generated />
using System;
using BumboApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BumboApp.Migrations
{
    [DbContext(typeof(BumboDbContext))]
    [Migration("20241127124838_InitialModule2")]
    partial class InitialModule2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BumboApp.Models.Availability", b =>
                {
                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("EmployeeNumber", "Date");

                    b.ToTable("Availabilities", t =>
                        {
                            t.HasCheckConstraint("CK_Availability_StartTime_EndTime", "[StartTime] < [EndTime]");
                        });

                    b.HasData(
                        new
                        {
                            EmployeeNumber = 1,
                            Date = new DateOnly(2024, 12, 9),
                            EndTime = new TimeOnly(17, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            EmployeeNumber = 2,
                            Date = new DateOnly(2024, 12, 10),
                            EndTime = new TimeOnly(17, 0, 0),
                            StartTime = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            EmployeeNumber = 3,
                            Date = new DateOnly(2024, 12, 11),
                            EndTime = new TimeOnly(14, 0, 0),
                            StartTime = new TimeOnly(8, 0, 0)
                        });
                });

            modelBuilder.Entity("BumboApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeNumber"));

                    b.Property<int>("ContractHours")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndOfEmployment")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LeaveHours")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartOfEmployment")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("EmployeeNumber");

                    b.HasIndex("UserId");

                    b.ToTable("Employees", t =>
                        {
                            t.HasCheckConstraint("CK_Employees_StartOfEmployment_EndOfEmployment", "[StartOfEmployment] <= [EndOfEmployment]");

                            t.HasCheckConstraint("CK_Employees_Zipcode", "[Zipcode] LIKE '[1-9][0-9][0-9][0-9][A-Z][A-Z]'");
                        });

                    b.HasData(
                        new
                        {
                            EmployeeNumber = 1,
                            ContractHours = 40,
                            DateOfBirth = new DateOnly(1990, 5, 20),
                            FirstName = "John",
                            HouseNumber = "1A",
                            LastName = "Doe",
                            LeaveHours = 60,
                            StartOfEmployment = new DateOnly(2020, 1, 15),
                            UserId = "1",
                            Zipcode = "1234AB"
                        },
                        new
                        {
                            EmployeeNumber = 2,
                            ContractHours = 20,
                            DateOfBirth = new DateOnly(1995, 8, 12),
                            FirstName = "Jane",
                            HouseNumber = "2B",
                            LastName = "Smith",
                            LeaveHours = 5,
                            StartOfEmployment = new DateOnly(2021, 3, 1),
                            UserId = "2",
                            Zipcode = "5684AC"
                        },
                        new
                        {
                            EmployeeNumber = 3,
                            ContractHours = 35,
                            DateOfBirth = new DateOnly(1998, 12, 5),
                            FirstName = "Emily",
                            HouseNumber = "3C",
                            LastName = "Jones",
                            LeaveHours = 40,
                            StartOfEmployment = new DateOnly(2019, 7, 30),
                            UserId = "3",
                            Zipcode = "5211DG"
                        });
                });

            modelBuilder.Entity("BumboApp.Models.Expectation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ExpectedCargo")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedCustomers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Expectations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 11, 18),
                            ExpectedCargo = 30,
                            ExpectedCustomers = 800
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 11, 19),
                            ExpectedCargo = 40,
                            ExpectedCustomers = 900
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 11, 20),
                            ExpectedCargo = 50,
                            ExpectedCustomers = 950
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 11, 21),
                            ExpectedCargo = 60,
                            ExpectedCustomers = 1000
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 11, 22),
                            ExpectedCargo = 45,
                            ExpectedCustomers = 850
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2024, 11, 23),
                            ExpectedCargo = 38,
                            ExpectedCustomers = 780
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2024, 11, 24),
                            ExpectedCargo = 55,
                            ExpectedCustomers = 960
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2024, 11, 25),
                            ExpectedCargo = 35,
                            ExpectedCustomers = 810
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2024, 11, 26),
                            ExpectedCargo = 50,
                            ExpectedCustomers = 900
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2024, 11, 27),
                            ExpectedCargo = 42,
                            ExpectedCustomers = 850
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2024, 11, 28),
                            ExpectedCargo = 60,
                            ExpectedCustomers = 1000
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2024, 11, 29),
                            ExpectedCargo = 37,
                            ExpectedCustomers = 820
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2024, 11, 30),
                            ExpectedCargo = 53,
                            ExpectedCustomers = 940
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2024, 12, 1),
                            ExpectedCargo = 50,
                            ExpectedCustomers = 900
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2024, 12, 2),
                            ExpectedCargo = 36,
                            ExpectedCustomers = 810
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2024, 12, 3),
                            ExpectedCargo = 47,
                            ExpectedCustomers = 870
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateOnly(2024, 12, 4),
                            ExpectedCargo = 38,
                            ExpectedCustomers = 780
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateOnly(2024, 12, 5),
                            ExpectedCargo = 55,
                            ExpectedCustomers = 950
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateOnly(2024, 12, 6),
                            ExpectedCargo = 45,
                            ExpectedCustomers = 840
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateOnly(2024, 12, 7),
                            ExpectedCargo = 60,
                            ExpectedCustomers = 1000
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateOnly(2024, 12, 8),
                            ExpectedCargo = 40,
                            ExpectedCustomers = 890
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateOnly(2024, 12, 9),
                            ExpectedCargo = 50,
                            ExpectedCustomers = 920
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateOnly(2024, 12, 10),
                            ExpectedCargo = 42,
                            ExpectedCustomers = 860
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateOnly(2024, 12, 11),
                            ExpectedCargo = 60,
                            ExpectedCustomers = 1000
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateOnly(2024, 12, 12),
                            ExpectedCargo = 48,
                            ExpectedCustomers = 930
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateOnly(2024, 12, 13),
                            ExpectedCargo = 35,
                            ExpectedCustomers = 780
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateOnly(2024, 12, 14),
                            ExpectedCargo = 53,
                            ExpectedCustomers = 950
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateOnly(2024, 12, 15),
                            ExpectedCargo = 50,
                            ExpectedCustomers = 900
                        });
                });

            modelBuilder.Entity("BumboApp.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber");

                    b.ToTable("LeaveRequests", t =>
                        {
                            t.HasCheckConstraint("CK_LeaveRequests_StartDate_EndDate", "[StartDate] <= [EndDate]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeNumber = 1,
                            EndDate = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Family event",
                            StartDate = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeNumber = 2,
                            EndDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Medical appointment",
                            StartDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("BumboApp.Models.Norm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NormType")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Norms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activity = 0,
                            CreatedAt = new DateTime(2024, 10, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NormType = 0,
                            Value = 5
                        },
                        new
                        {
                            Id = 2,
                            Activity = 1,
                            CreatedAt = new DateTime(2024, 10, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NormType = 1,
                            Value = 30
                        },
                        new
                        {
                            Id = 3,
                            Activity = 2,
                            CreatedAt = new DateTime(2024, 10, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NormType = 2,
                            Value = 30
                        },
                        new
                        {
                            Id = 4,
                            Activity = 3,
                            CreatedAt = new DateTime(2024, 10, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NormType = 2,
                            Value = 100
                        },
                        new
                        {
                            Id = 5,
                            Activity = 4,
                            CreatedAt = new DateTime(2024, 10, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NormType = 3,
                            Value = 30
                        });
                });

            modelBuilder.Entity("BumboApp.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<bool>("HasBeenRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Don't forget the department meeting on Dec 10.",
                            EmployeeNumber = 1,
                            HasBeenRead = false,
                            SentAt = new DateTime(2024, 12, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Meeting Reminder"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Check your holiday hours for December.",
                            EmployeeNumber = 3,
                            HasBeenRead = true,
                            SentAt = new DateTime(2024, 12, 7, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Holiday Hours"
                        });
                });

            modelBuilder.Entity("BumboApp.Models.OpeningHour", b =>
                {
                    b.Property<int>("WeekDay")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("OpeningTime")
                        .HasColumnType("time");

                    b.HasKey("WeekDay");

                    b.ToTable("OpeningHours", t =>
                        {
                            t.HasCheckConstraint("CK_OpeningHours_OpeningTime_ClosingTime", "([OpeningTime] IS NULL AND [ClosingTime] IS NULL) OR ([OpeningTime] IS NOT NULL AND [ClosingTime] IS NOT NULL AND [OpeningTime] < [ClosingTime])");
                        });

                    b.HasData(
                        new
                        {
                            WeekDay = 1,
                            ClosingTime = new TimeOnly(21, 0, 0),
                            OpeningTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            WeekDay = 2,
                            ClosingTime = new TimeOnly(21, 0, 0),
                            OpeningTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            WeekDay = 3,
                            ClosingTime = new TimeOnly(21, 0, 0),
                            OpeningTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            WeekDay = 4,
                            ClosingTime = new TimeOnly(21, 0, 0),
                            OpeningTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            WeekDay = 5,
                            ClosingTime = new TimeOnly(21, 0, 0),
                            OpeningTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            WeekDay = 6,
                            ClosingTime = new TimeOnly(20, 0, 0),
                            OpeningTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            WeekDay = 0
                        });
                });

            modelBuilder.Entity("BumboApp.Models.Prognosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<float>("NeededEmployees")
                        .HasColumnType("real");

                    b.Property<float>("NeededHours")
                        .HasColumnType("real");

                    b.Property<int>("WeekPrognosisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeekPrognosisId");

                    b.HasIndex("Date", "Department")
                        .IsUnique();

                    b.ToTable("Prognoses", t =>
                        {
                            t.HasCheckConstraint("CK_Prognoses_NeededHours_NeededEmployees", "[NeededHours] = [NeededEmployees] * 8");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 10, 7),
                            Department = 0,
                            NeededEmployees = 5f,
                            NeededHours = 40f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 10, 7),
                            Department = 1,
                            NeededEmployees = 4f,
                            NeededHours = 32f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 10, 7),
                            Department = 2,
                            NeededEmployees = 3f,
                            NeededHours = 24f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 10, 8),
                            Department = 0,
                            NeededEmployees = 4f,
                            NeededHours = 32f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 10, 8),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 24f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2024, 10, 8),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 16f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2024, 10, 9),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 48f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2024, 10, 9),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 24f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2024, 10, 9),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 16f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2024, 10, 10),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 48f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2024, 10, 10),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 24f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2024, 10, 10),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 16f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2024, 10, 11),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 48f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2024, 10, 11),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 24f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2024, 10, 11),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 16f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2024, 10, 12),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 48f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateOnly(2024, 10, 12),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 24f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateOnly(2024, 10, 12),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 16f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateOnly(2024, 10, 13),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 48f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateOnly(2024, 10, 13),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 24f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateOnly(2024, 10, 13),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 16f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateOnly(2024, 12, 9),
                            Department = 0,
                            NeededEmployees = 5f,
                            NeededHours = 40f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateOnly(2024, 12, 9),
                            Department = 1,
                            NeededEmployees = 4.5f,
                            NeededHours = 36f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateOnly(2024, 12, 9),
                            Department = 2,
                            NeededEmployees = 2.5f,
                            NeededHours = 20f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateOnly(2024, 12, 10),
                            Department = 0,
                            NeededEmployees = 4f,
                            NeededHours = 32f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateOnly(2024, 12, 10),
                            Department = 1,
                            NeededEmployees = 3.5f,
                            NeededHours = 28f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateOnly(2024, 12, 10),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 16f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateOnly(2024, 12, 11),
                            Department = 0,
                            NeededEmployees = 5f,
                            NeededHours = 40f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateOnly(2024, 12, 11),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 24f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateOnly(2024, 12, 11),
                            Department = 2,
                            NeededEmployees = 2.5f,
                            NeededHours = 20f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateOnly(2024, 12, 12),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 48f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateOnly(2024, 12, 12),
                            Department = 1,
                            NeededEmployees = 4.5f,
                            NeededHours = 36f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateOnly(2024, 12, 12),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 16f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateOnly(2024, 12, 13),
                            Department = 0,
                            NeededEmployees = 5f,
                            NeededHours = 40f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateOnly(2024, 12, 13),
                            Department = 1,
                            NeededEmployees = 3.5f,
                            NeededHours = 28f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateOnly(2024, 12, 13),
                            Department = 2,
                            NeededEmployees = 1.5f,
                            NeededHours = 12f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateOnly(2024, 12, 14),
                            Department = 0,
                            NeededEmployees = 4f,
                            NeededHours = 32f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateOnly(2024, 12, 14),
                            Department = 1,
                            NeededEmployees = 5f,
                            NeededHours = 40f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateOnly(2024, 12, 14),
                            Department = 2,
                            NeededEmployees = 3f,
                            NeededHours = 24f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateOnly(2024, 12, 15),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 48f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateOnly(2024, 12, 15),
                            Department = 1,
                            NeededEmployees = 4f,
                            NeededHours = 32f,
                            WeekPrognosisId = 2
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateOnly(2024, 12, 15),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 16f,
                            WeekPrognosisId = 2
                        });
                });

            modelBuilder.Entity("BumboApp.Models.SchoolSchedule", b =>
                {
                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<float>("DurationInHours")
                        .HasColumnType("real");

                    b.HasKey("EmployeeNumber", "Date");

                    b.ToTable("SchoolSchedules");

                    b.HasData(
                        new
                        {
                            EmployeeNumber = 1,
                            Date = new DateOnly(2024, 12, 9),
                            DurationInHours = 4f
                        },
                        new
                        {
                            EmployeeNumber = 1,
                            Date = new DateOnly(2024, 12, 10),
                            DurationInHours = 4f
                        },
                        new
                        {
                            EmployeeNumber = 2,
                            Date = new DateOnly(2024, 12, 9),
                            DurationInHours = 3f
                        },
                        new
                        {
                            EmployeeNumber = 2,
                            Date = new DateOnly(2024, 12, 10),
                            DurationInHours = 3f
                        },
                        new
                        {
                            EmployeeNumber = 3,
                            Date = new DateOnly(2024, 12, 9),
                            DurationInHours = 6f
                        },
                        new
                        {
                            EmployeeNumber = 3,
                            Date = new DateOnly(2024, 12, 10),
                            DurationInHours = 6f
                        });
                });

            modelBuilder.Entity("BumboApp.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber");

                    b.ToTable("Shifts", t =>
                        {
                            t.HasCheckConstraint("CK_Shifts_Start_End", "[Start] < [End]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 2,
                            EmployeeNumber = 1,
                            End = new DateTime(2024, 12, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinal = false,
                            Start = new DateTime(2024, 12, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Department = 1,
                            EmployeeNumber = 2,
                            End = new DateTime(2024, 12, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinal = false,
                            Start = new DateTime(2024, 12, 10, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BumboApp.Models.ShiftTakeOver", b =>
                {
                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeTakingOverEmployeeNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ShiftId");

                    b.HasIndex("EmployeeTakingOverEmployeeNumber");

                    b.ToTable("ShiftTakeOvers");

                    b.HasData(
                        new
                        {
                            ShiftId = 2,
                            EmployeeTakingOverEmployeeNumber = 3,
                            Status = 0
                        },
                        new
                        {
                            ShiftId = 1,
                            EmployeeTakingOverEmployeeNumber = 2,
                            Status = 2
                        });
                });

            modelBuilder.Entity("BumboApp.Models.SickLeave", b =>
                {
                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("EmployeeNumber", "Date");

                    b.ToTable("SickLeaves");
                });

            modelBuilder.Entity("BumboApp.Models.UniqueDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<float>("Factor")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("UniqueDays", t =>
                        {
                            t.HasCheckConstraint("CK_UniqueDays_StartDate_EndDate", "[StartDate] <= [EndDate]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateOnly(2024, 11, 22),
                            Factor = 1.25f,
                            Name = "Customer Appreciation Day",
                            StartDate = new DateOnly(2024, 11, 22)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateOnly(2024, 11, 29),
                            Factor = 1.5f,
                            Name = "VIP Shopping Day",
                            StartDate = new DateOnly(2024, 11, 29)
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateOnly(2024, 12, 8),
                            Factor = 1.8f,
                            Name = "Weekend Sale",
                            StartDate = new DateOnly(2024, 12, 7)
                        });
                });

            modelBuilder.Entity("BumboApp.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("BumboApp.Models.WeekPrognosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .IsUnique();

                    b.ToTable("WeekPrognoses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StartDate = new DateOnly(2024, 10, 7)
                        },
                        new
                        {
                            Id = 2,
                            StartDate = new DateOnly(2024, 12, 9)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BumboApp.Models.Availability", b =>
                {
                    b.HasOne("BumboApp.Models.Employee", "Employee")
                        .WithMany("Availabilities")
                        .HasForeignKey("EmployeeNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BumboApp.Models.Employee", b =>
                {
                    b.HasOne("BumboApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BumboApp.Models.LeaveRequest", b =>
                {
                    b.HasOne("BumboApp.Models.Employee", "Employee")
                        .WithMany("leaveRequests")
                        .HasForeignKey("EmployeeNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BumboApp.Models.Notification", b =>
                {
                    b.HasOne("BumboApp.Models.Employee", "Employee")
                        .WithMany("notifications")
                        .HasForeignKey("EmployeeNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BumboApp.Models.Prognosis", b =>
                {
                    b.HasOne("BumboApp.Models.WeekPrognosis", null)
                        .WithMany("Prognoses")
                        .HasForeignKey("WeekPrognosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BumboApp.Models.SchoolSchedule", b =>
                {
                    b.HasOne("BumboApp.Models.Employee", "Employee")
                        .WithMany("SchoolSchedules")
                        .HasForeignKey("EmployeeNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BumboApp.Models.Shift", b =>
                {
                    b.HasOne("BumboApp.Models.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeNumber");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BumboApp.Models.ShiftTakeOver", b =>
                {
                    b.HasOne("BumboApp.Models.Employee", "EmployeeTakingOver")
                        .WithMany("shiftTakeOvers")
                        .HasForeignKey("EmployeeTakingOverEmployeeNumber");

                    b.HasOne("BumboApp.Models.Shift", "Shift")
                        .WithOne("ShiftTakeOver")
                        .HasForeignKey("BumboApp.Models.ShiftTakeOver", "ShiftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EmployeeTakingOver");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("BumboApp.Models.SickLeave", b =>
                {
                    b.HasOne("BumboApp.Models.Employee", "Employee")
                        .WithMany("sickLeaves")
                        .HasForeignKey("EmployeeNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BumboApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BumboApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BumboApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BumboApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BumboApp.Models.Employee", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("SchoolSchedules");

                    b.Navigation("Shifts");

                    b.Navigation("leaveRequests");

                    b.Navigation("notifications");

                    b.Navigation("shiftTakeOvers");

                    b.Navigation("sickLeaves");
                });

            modelBuilder.Entity("BumboApp.Models.Shift", b =>
                {
                    b.Navigation("ShiftTakeOver")
                        .IsRequired();
                });

            modelBuilder.Entity("BumboApp.Models.WeekPrognosis", b =>
                {
                    b.Navigation("Prognoses");
                });
#pragma warning restore 612, 618
        }
    }
}
