// <auto-generated />
using System;
using BumboApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BumboApp.Migrations
{
    [DbContext(typeof(BumboDbContext))]
    [Migration("20241010090042_SeedPrognosisData")]
    partial class SeedPrognosisData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BumboApp.Models.Expectation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ExpectedCargo")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedCustomers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Expectations");
                });

            modelBuilder.Entity("BumboApp.Models.Norm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NormType")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Norms");
                });

            modelBuilder.Entity("BumboApp.Models.OpeningHour", b =>
                {
                    b.Property<string>("WeekDay")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time");

                    b.HasKey("WeekDay");

                    b.ToTable("OpeningHours");
                });

            modelBuilder.Entity("BumboApp.Models.Prognosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<float>("NeededEmployees")
                        .HasColumnType("real");

                    b.Property<float>("NeededHours")
                        .HasColumnType("real");

                    b.Property<int>("WeekPrognosisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeekPrognosisId");

                    b.ToTable("Prognoses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 10, 7),
                            Department = 0,
                            NeededEmployees = 5f,
                            NeededHours = 40f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 10, 7),
                            Department = 1,
                            NeededEmployees = 4f,
                            NeededHours = 35f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 10, 7),
                            Department = 2,
                            NeededEmployees = 3f,
                            NeededHours = 30f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 10, 8),
                            Department = 0,
                            NeededEmployees = 4f,
                            NeededHours = 38f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 10, 8),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 37f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2024, 10, 8),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 28f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2024, 10, 9),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 42f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2024, 10, 9),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 32f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2024, 10, 9),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 26f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2024, 10, 10),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 42f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2024, 10, 10),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 32f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2024, 10, 10),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 26f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2024, 10, 11),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 42f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2024, 10, 11),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 32f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2024, 10, 11),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 26f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2024, 10, 12),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 42f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateOnly(2024, 10, 12),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 32f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateOnly(2024, 10, 12),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 26f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateOnly(2024, 10, 13),
                            Department = 0,
                            NeededEmployees = 6f,
                            NeededHours = 42f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateOnly(2024, 10, 13),
                            Department = 1,
                            NeededEmployees = 3f,
                            NeededHours = 32f,
                            WeekPrognosisId = 1
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateOnly(2024, 10, 13),
                            Department = 2,
                            NeededEmployees = 2f,
                            NeededHours = 26f,
                            WeekPrognosisId = 1
                        });
                });

            modelBuilder.Entity("BumboApp.Models.UniqueDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<float>("Factor")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("UniqueDays");
                });

            modelBuilder.Entity("BumboApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BumboApp.Models.WeekPrognosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("WeekPrognoses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StartDate = new DateOnly(2024, 10, 7)
                        });
                });

            modelBuilder.Entity("BumboApp.Models.Prognosis", b =>
                {
                    b.HasOne("BumboApp.Models.WeekPrognosis", null)
                        .WithMany("Prognoses")
                        .HasForeignKey("WeekPrognosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BumboApp.Models.WeekPrognosis", b =>
                {
                    b.Navigation("Prognoses");
                });
#pragma warning restore 612, 618
        }
    }
}
